### PR TITLE
WIP: WPF TrayIcon

### PR DESCRIPTION
**Pull request by Blinke**
I'm not sure if this PR is ready to merge yet, but I'm putting it up here now for the sake of discussion.

Using [this](https://github.com/hardcodet/wpf-notifyicon) nifty library I've been able to replace the old tray icon with a WPF version. This means the new entry point of the application is `App.xaml.cs` instead of `Main`. The contents should look pretty familiar for now though.

Most things should be working as usual apart from notifications. Need to figure out a good way to handle those. 

Points to discuss:
* MVVM: should we try to follow it? I used it for the tray icon and my opinion is that we should try to stick to it everywhere. Separating business logic from the GUI with data binding and commands is super helpful for testing.
* Should we use [Fody](https://github.com/Fody/PropertyChanged) to handle implementing `INotifyPropertyChanged`? I've used it in the past and it's been tremendously helpful.
* Other thoughts or questions.

Disclaimer: I'm not by any means a WPF expert. I've made a couple of small applications for work but I'm primarily a backend developer.

### CODE REVIEW

**Comment by domialex** [comment]
@Blinke Can you re-pull?

**Comment by Blinke** [comment]
About to go to sleep, will do in the morning.

**Comment by domialex** [comment]
Will this function properly with .NET Core?

**Comment by leMicin** [comment]
I don't like the fact that you changed the LeagueService to trigger an event when the List is modified. There must be another way. If we start doing things this way, we will have Events everywhere.

For the leagues, you can hook into IOnAfterInit hook as the league data is initialized on the OnInit step.

**Comment by Blinke** [comment]
@domialex Everything I've added is pure WPF and should be. NET compatible. WPF is not cross-platform right now so this PR doesn't contribute directly to any efforts to make Sidekick cross-platform. AvaloniaUI might be a good candidate for that and porting the current code could be made a little easier by doing this WPF transition now and figuring out a good structure.

Regarding the LeagueService event thing, I was a bit hesitant to include the view model in that init flow. It's possible that that uncertainty is unjustified, I can certainly change that.

**Pull request merged**
