### PR TITLE
Gem Support

### PR DESCRIPTION
**Pull request by Zalhera**
Added Support for Gems. Started Implementation for Misc Filters. Fixed a small bug when there is no listed price.

### CODE REVIEW

**Comment by jovanmhn** [comment]
Our commits will clash :) Kinda

Did you find any proper documentation for the actual API classes, i was working off of some random JSON query I found online (https://jsoncompare.com/#!/simple/id=70dfadce047d9ea0c9e509dd6e85e84e&fullscreen/)

**Comment by Zalhera** [comment]
I worked off the same JSON query as you ;D
Yeah but I think it's possible to merge both our requests without to much effort.
I'm also working on the filter properties at the moment.

**Comment by jovanmhn** [comment]
I had the idea of leaving all the classes and their properties named as they are in that JSON, purely because its easier to keep track of what is what, especially if things change in the future.

It will violate some naming conventions, but to be honest, in modern IDEs, its all colored anyway, I personally dont care about capitalization much.

I am not sure what @domialex thinks about this, but either way, we could maybe split the work on the filters, as it is the key feature thats missing, in my opinion.

**Comment by Zalhera** [comment]
Yeah I think the naming convention is more of a personal for preference from me in this case.
I already implemented the basic filter structure, but I'm having some problems with specific things like influence and non-unique items at the moment.

@jovanmhn if you're interested I can open a new pull request with the filter changes so you can work of that.

I was thinking about trying to start building the advanced search options, so you can filter for specific affixes on an item.

**Comment by domialex** [comment]
Just so you guys know, my idea for the query builder is to make a factory with lambda expressions that can add attributes based on https://www.pathofexile.com/api/trade/data/stats which is currently stored in `TradeClient.AttributeCategories`. I am working on it.

**Comment by domialex** [comment]
@Zalhera Sorry about the conflicts, lots of PRs today. Would you mind fixing them? I will merge asap.

**Comment by Zalhera** [comment]
@domialex I fixed the conflicts.
Could you tell me and @jovanmhn  what your opinion on the naming strategy for the json objects is?

**Comment by domialex** [comment]
I also try to keep the same names as the json results, it's easier to follow like this.

**Comment by domialex** [comment]
Resolves #12

**Pull request merged**
