### PR TITLE
Overlay for rare price prediction

### PR DESCRIPTION
**Pull request by Zalhera**
Price Prediction only works with english item text

### CODE REVIEW

**Comment by leMicin** [comment]
This is a feature I use a lot in TradeMacro. It is not always right, but it helps

**Comment by domialex** [comment]
Unfortunately, while this is a feature I want in Sidekick, that is not the way I had in mind.
Let me explain with my incredible paint skills : https://i.imgur.com/i0xPSem.png
Also, we could probably support multiple languages by having all item names somewhere [like this guy did](https://github.com/gvieiraaa/PoETranslator), there doesn't seem to be another way.

**Comment by domialex** [comment]
Related to #129, #128 and #50.

**Comment by leMicin** [comment]
I think both could be inside sidekick. For the advanced users, I agree that the price prediction can be hit or miss. But personnally, as a "new user" this league, I found it extremely useful. I didn't know what stats were worth money on what items. I now know a rough idea of what an item could be worth because of the services of poeprices.info . I think this needs reconsideration.

**Comment by domialex** [comment]
@Zalhera @leMicin Let me be clear, the feature will be in Sidekick, I just didn't want a view just for this.
Can this be a solution? https://i.imgur.com/6EsTkoI.png

**Comment by Zalhera** [comment]
The problem I see with your solution is that the listed items will probably not reflect the predicted price correctly.
I just mirrored the functionality and overlay layout from Poe Trade Macro

**Comment by domialex** [comment]
> listed items will probably not reflect the predicted price

Just to make sure, the top right info would only take into consideration the item we originally Ctrl+D'ed. Is there a problem with this idea? @leMicin suggested that maybe the new overlay could be opened with this link instead of going directly to poeprices.info.

The only thing that I don't want, is that when we price check a rare item, it **always** choses this new overlay with poeprices...I think it's more elegant to make the current overlay handle the first step of the workflow in all scenarios.

**Comment by domialex** [comment]
I've decided that we still need the overlay in any case so good PR 👍.

**Pull request merged**
