### PR TITLE
Implemented simple single instance HttpClient Provider, not the best …

### PR DESCRIPTION
**Pull request by MarcosGitDev**
Implemented simple single instance HttpClient Provider, not the best implementation, but one of the quickest and easiest to maintain.

### CODE REVIEW

**Comment by cricket1650** [comment]
It's a good quick fix. When #97 is finished we can replace this with dependency injection and the HttpClientFactory.

**Comment by domialex** [comment]
> It's a good quick fix. When #97 is finished we can replace this with dependency injection and the HttpClientFactory.

Was going to link to the same issue. Thanks.

**Comment by domialex** [comment]
You PR didn't build so I pushed something real quick to fix it.

**Comment by MarcosGitDev** [comment]
thx domialex, i probably didn't properly resolve the conflicts when merging since my branch was building, my bad.

**Pull request merged**
