### PR TITLE
Convert csproj file to new/terse format

### PR DESCRIPTION
**Pull request by jonstelly**
Convert csproj file to new format.  At the very least the new csproj format is easier to read and less prone to merge conflicts which should reduce headaches on pull requests.  But it also sets the stage for targeting .net core 3.0 and producing a [fully self-contained single executable](https://dotnetcoretutorials.com/2019/06/20/publishing-a-single-exe-file-in-net-core-3-0/), eliminating the need to have users install the .NET Framework.

There are two things that need to happen before Sidekick could target .net core 3.0:

1. There are a couple dependencies on System.Windows.Forms (context menu, tray icon, etc...) that would need to be replaced
2. [MouseKeyHook](https://github.com/gmamaladze/globalmousekeyhook) would need to be ported to .net core or .net standard.  I haven't dug into MouseKeyHook yet but I'll try to do that some time this week.

From first glance it looks like MouseKeyHook has a dependency on System.Windows.Forms and uses some of the Windows Forms Key enumerations.  I'll take a look at converting that library to .net core, might be easy enough to clone the Forms enums into the library for a .net core/standard build.

Resolves: https://github.com/domialex/Sidekick/issues/29

### CODE REVIEW

**Comment by jonstelly** [comment]
I got a build error when merging changes from master here... https://github.com/domialex/Sidekick/blame/master/source/Helpers/ItemParser.cs#L46 - I don't see a `GetLinks()` implementation in ItemParser

**Comment by domialex** [comment]
> I got a build error when merging changes from master here... https://github.com/domialex/Sidekick/blame/master/source/Helpers/ItemParser.cs#L46 - I don't see a `GetLinks()` implementation in ItemParser

Pull from master it should be fixed.

**Comment by jonstelly** [comment]
That did it, thanks.  This should be good to go.

One note, when this gets merged it will require developers to have [the .NET Core 3.0/3.1 SDK installed](https://dotnet.microsoft.com/download/dotnet-core/3.1).  Either by installing the feature in VS 2019 or installing the SDK separately

**Comment by domialex** [comment]
> That did it, thanks. This should be good to go.
> 
> One note, when this gets merged it will require developers to have [the .NET Core 3.0/3.1 SDK installed](https://dotnet.microsoft.com/download/dotnet-core/3.1). Either by installing the feature in VS 2019 or installing the SDK separately

Remember to delete the /packages folder locally if you have build problems.

**Pull request merged**
