### PR TITLE
Features/144 prices

### PR DESCRIPTION
**Pull request by leMicin**
Putting the PR up so others can view the progress of the price check view model.

Please let me know on Discord if you wish to try and make progress.
Between 1AM and 5PM EST, you do not need to wait for me to answer as I will be sleeping and/or working.

This branch does not currently compile.

### CODE REVIEW

**Comment by leMicin** [comment]
Fixes #144 #141

**Comment by leMicin** [comment]
This is now ready for review.

**Comment by leMicin** [comment]
Fixes #140 also

**Comment by Blinke** [comment]
A lot to look through but I think it looks really good. Two issues I found:

- Price check window is not constrained to the screen. It can poke out of the top or left side of the screen.
- Opening a new league overlay or doing a new price check doesn't close the previously opened window, you have to do it manually.

**Comment by domialex** [comment]
Merged some cleanups from #242.

**Comment by leMicin** [comment]
Fixed both issues. Thanks for pointing them out Blinke :)

**Pull request merged**
