### PR TITLE
Add support for soft-coded hotkeys

### PR DESCRIPTION
**Pull request by cricket1650**
This allows us to add an indefinite amount of hotkeys without having large if/else blocks.

It will obviously be more useful when we add a config to the application.

### CODE REVIEW

**Comment by domialex** [comment]
@cricket1650 Can you change the hideout to F5 instead of F?

**Comment by cricket1650** [comment]
I fixed that typo. It looks like this will conflict with the changes to the config page. We will have to decide which one goes first.

**Comment by domialex** [comment]
I think it will be easier to adapt this one if it goes after #83 .

**Comment by cricket1650** [comment]
Agreed

**Comment by domialex** [comment]
@cricket1650 Alright the other one is merged, sorry about the conflicts. You have a free rein over that file if you want. (cleanup, refactor, login, etc.)

**Comment by cricket1650** [comment]
Going to close this for now. In order to do this properly it will require rewriting much of the settings page and I don't think it is worth the effort atm. Maybe once we have the restructure from #97.

**Comment by domialex** [comment]
Yea sorry about that, when #97 is done it should be easier to collaborate from that point.

**Pull request closed without merging**
