### PR TITLE
Advanced Search

### PR DESCRIPTION
**Pull request by Zalhera**
Started parsing Attributes from Items

- [ ] Attribute Parsing
   - [x] Implicit
   - [x] Explicit
   - [x] Crafted
   - [x] Enchant
   - [ ] Annointment
- [x] Query Parsing
- [ ] Advanced Search UI
   - [x] Base UI Layout
   - [ ] UI Translation
   - [x] Min/Max Values 
   - [ ] Sockets
   - [ ] Links
   - [ ] Item Level
   - [ ] Influence
   - [ ] DPS/Armor
- [ ] Language Support
   - [x] English
   - [ ] German
   - [ ] Spanish
   - [ ] French
   - [ ] Korean
   - [ ] Portuguese
   - [ ] Russian
   - [ ] Thai
   - [ ] Traditional Chinese

### CODE REVIEW

**Comment by Zalhera** [comment]
Started on parsing Item Attributes to the UI

**Comment by domialex** [comment]
The item parser changed a bit with #242, might want to pull from the head branch.

**Comment by Zalhera** [comment]
@domialex  can you merge #242 into the develop branch?
With all the things that @leMicin is reworking in his branch it's very difficult for me to follow everything.

**Comment by Zalhera** [comment]
Closing this and PR and open it on a clean branch

**Pull request closed without merging**
