### PR TITLE
Delve Overview Fix + Started Translation

### PR DESCRIPTION
**Pull request by Zalhera**
Added new Vagan rewards on Betrayal Window
Started Translating Resource files to german:

- [x] Betrayal
- [x] Blight
- [x] Delve
- [x] Incursion
- [x] Metamorph

### CODE REVIEW

**Comment by leMicin** [comment]
Awesome, keep up the good work! Also can you have a look here : https://github.com/domialex/Sidekick/issues/206

You might be able to do that with this commit?

**Comment by Zalhera** [comment]
@leMicin I already included the updated rewards from #206

**Comment by leMicin** [comment]
@Zalhera Awesome!

**Comment by Zalhera** [comment]
@leMicin you can merge if you want
I will update the view controls in the next few days

**Pull request merged**
