### PR TITLE
Add space key to close overlay

### PR DESCRIPTION
**Pull request by Qwiso**
Spacebar feels much nicer to use because PoE uses this by default to close the UI

Simple QoL

### CODE REVIEW

**Comment by Qwiso** [comment]
Ref: #61

**Comment by Qwiso** [comment]
- should overlay remain open if spacebar is used while typing a message? 
- implement focus/blur logic for overlay

**Comment by Zalhera** [comment]
I think changing the hotkey to close to the overlay should be implemented in combination with #7 so the user can choose the preferred hotkey for himself.
The color change for corrupted item is nice tho.

**Comment by anonmonogatari** [comment]
This won't do. Space key is a common hotkey for lots of builds most commonly used in builds that uses weapon swap or 5th flask. 

Better implementation would be option to choose hotkey for it on settings GUI when it's done.

**Comment by domialex** [comment]
@anonmonogatari When Sidekick detects a hotkey while the overlay is opened, it will block that key from being sent to the rest of Windows. So if someone presses `space`, it won't happen in PoE.
@Qwiso Someone is doing #7 right now, so this PR will won't be necessary.
As for the corrupted attribute, it would be wiser to actually display "Corrupted" under the item name, just like in the game.

**Pull request closed without merging**
