### PR TITLE
Language Support for all PoE Client Languages

### PR DESCRIPTION
**Pull request by Zalhera**
Also small Bugfix for searching divination cards in bulk exchange.

### CODE REVIEW

**Comment by domialex** [comment]
Can you make another pull request only for develop?

**Comment by lascoin** [comment]
What is the go to way to extract correctly localized and formatted strings for all these languages now when adding StringConsts?

**Comment by domialex** [comment]
@lascoin For now it's in `LanguageProviders.cs`, in the future we will use resx files and dynamically change the culture of the ui when scanning an item. So Sidekick will be translated automatically when a user tries to scan an item.

**Comment by lascoin** [comment]
Yes I can see where the StringConsts were moved, my question was more in terms of when I for example wanted to add `public string DescriptionExperience => "Experience: ";` into the LanguageProviders, these need to be added for all extenders of the interface. 

In this case, it was used to parse gem xp information by string, but finding out what "Experience:" is tagged as for all languages  (especially non latin character languages like kr, th, ru) is extremely tedious and google translate would not be safe enough imo.

So how would I find the correct PoE native formatting of this string when adding this for all other locales?

**Comment by domialex** [comment]
@Zalhera Can you show your method of getting the languages for all the tags?

**Comment by Zalhera** [comment]
@lascoin I just copied the item information from the english client for reference and then did the same for all other client languages and compared the item lines which I needed to translate.
But I can do the same for the gem experience, etc. in a later pull request if you want.

**Pull request closed without merging**
