### PR TITLE
League Overlay Blight + Metamorph

### PR DESCRIPTION
**Pull request by Zalhera**

### CODE REVIEW

**Comment by domialex** [comment]
Those images should come from `https://www.pathofexile.com/api/trade/data/static` (currencies) and not static files. Also, I'm starting to question why we need to have all those images for Betrayal as well. Couldn't we just have 1 image for the Betrayal characters at the top? Think about it, in the end we're going to have to maintain hundreds of texts and images every season.

**Comment by Zalhera** [comment]
And how should we fetch these images?
I don't understand the problem for the betrayal images, because this content will not get changed anymore so we don't have to maintain this page or other pages of past leagues. (Excluding changes to functionality which would just be text)

**Comment by domialex** [comment]
For the images, they're all in the `StaticItemCategoryService`, the `StaticItem` class has the image url. You just append this url to the `PoeCdnBaseUrl` from the Language service.
For the Betrayal images, remember that we want to port to .NET Core 3 into a single executable file, we don't want to publish Sidekick with an img folder ideally.

**Comment by Zalhera** [comment]
Yes I'm planning to move the Images into a single Resource File which will not the deployed with Sidekick itself but wanted to finish the Overlay Pages first.
I still don't think it's a good idea to fetch the images from the API itself, because it will just add more loading time to the tool.

**Comment by domialex** [comment]
> I still don't think it's a good idea to fetch the images from the API itself, because it will just add more loading time to the tool.

The advantage of doing this is not having to maintain images, be less dependant on changes from PoE, even though a lot of data is very conditionally parsed in most cases :(. In #50, I will fetch the currencies from the API, and from my early messing around, it was instant.

**Comment by domialex** [comment]
There is a problem though, we still haven't figured out a good way to have DI in our WPF yet. @leMicin do we just go with it and do it later?

**Comment by Zalhera** [comment]
Okay I will test loading the images from the API later today and give feedback on how fast the loading times are.

**Comment by domialex** [comment]
Meh, I've thought about it, and nothing's set in stone so it's not a problem either way.

**Pull request merged**
