### PR TITLE
Added a close button to UI

### LINKED ISSUE #106: Add settings to decide how the overlay should close
Some people want the overlay to automatically close with a click outside of the overlay, or when the mouse moves a certain distance. This should be a setting.

### PR DESCRIPTION
**Pull request by hseager**
I've added a small close button to the top right of the UI like in the screenshot below.

https://imgur.com/aYkqAYc

It also closes when pressing 'Esc' by using the IsCancel="True" flag.

Might be enough to close #106.

### CODE REVIEW

**Comment by cmos12345** [comment]
Now this is just my opinion, but I'd rather be able to click anywhere on the screen outside of the overlay to close it, than having to aim for a tiny close button.

**Comment by domialex** [comment]
> Now this is just my opinion, but I'd rather be able to click anywhere on the screen outside of the overlay to close it, than having to aim for a tiny close button.

I've updated #106 with a better description.

Also, in this PR, the **Escape** hotkey will only work if the overlay has focus, and also makes it weird if someone changed the hotkey to something else entirely.
Thanks for the contribution, but unless we allow multiple Overlays in the future, I'm not sure this is needed. I will keep the idea in mind.

**Comment by hseager** [comment]
With my initial testing the Escape key wasn't working to close the overlay and the only way to close it was to right click the tray icon and exit which was pretty frustrating (I might raise this as a bug after more testing).

I'm sure there's a better way to bind the escape key and have it configurable like you say, but personally having a close button in the top right is habitual. 

Although it might be better to close when clicking outside of the window like you say in #106.

**Comment by domialex** [comment]
Right now in the develop branch, it's the **Space** key that closes the overlay lol.

**Comment by hseager** [comment]
> Right now in the develop branch, it's the Space key that closes the overlay lol.

Ah right, that would be why :D

**Pull request closed without merging**
