### PR TITLE
Proposal to switch to standard DI pattern

### PR DESCRIPTION
**Pull request by Blinke**
While the current DI solution based on properties is neat, I propose we switch to the boring old way of registering dependencies :)

This would lower barrier of entry for contributors as they are more likely to be familiar with the structure as well as reduce complexity and clutter in the solution. I also moved the registering of the dependencies to the `Sidekick` project as that is the appropriate layer to handle it in.

Related to #97

### CODE REVIEW

**Comment by leMicin** [comment]
I like this argument : "This would lower barrier of entry for contributors as they are more likely to be familiar with the structure as well as reduce complexity and clutter in the solution"

For that reason alone, I agree with your proposal. Though I don't like where the AddSidekickServices code is located. In the event we have multiple consuming projects, each project will need to implement its own AddSidekickServices. I would prefer if that method is moved inside the projects where the service is located. Exemples:
- AddSidekickCoreServices() //  For services inside Sidekick.Core
- AddSidekickBusinessServices() //  For services inside Sidekick.Business
- AddSidekickServices() // For services inside Sidekick

**Comment by Blinke** [comment]
I didn't think too hard about having a different consuming project. It doesn't feel like something that would be terrible likely to exist in the future, but maybe I'm wrong.

Having to duplicate the service registration for other eventual projects is a slight hassle, sure. Whenever the scenario has come up at work there has never been a clean separation of dependencies that would always go together. There's always been some mixing and matching that didn't lend itself well to any particular way of grouping.

My view is that a consuming project should have full responsibility of choosing implementations and not have to rely on predefined groups. Not a huge deal though so I can go either way :)

**Comment by leMicin** [comment]
I am going to refer to some official .NetCore code and an exemple of what I want.

Here is the source code for the .AddIdentity helper method.
https://github.com/dotnet/aspnetcore/blob/555b506a97a188583df2872913cc40b59e563da6/src/Identity/Core/src/IdentityServiceCollectionExtensions.cs#L81
You can see near line 81 where it adds multiple services.

If a consuming project does not need all the services or requires a different implementation, then that service can simply not call the AddSidekickBusinessServices(). It is still flexible, while offering an easy way.

And we are thinking of doing multiple consuming projects to support multiple platforms. Sidekick currently only supports Windows, but we are exploring ways to make other platforms available through different UI projects.

**Comment by Blinke** [comment]
Fair enough! I can be in board with that.

**Comment by domialex** [comment]
Oh man I prefer this way ahah, personal preference ;)

**Pull request merged**
