### PR TITLE
League Overview Betrayal

### PR DESCRIPTION
**Pull request by Zalhera**
Started with the League Overlay Window.
Implemented Basic GUI for Betrayal Overview with Language support.

TODO:
 - Tooltips on Mouse Over with Multiple Language Support
 - Use Mouse Wheel to scroll between League Overlay Tabs
 - Wiki Support (Maybe?)
 - User Rarity Configuration

### CODE REVIEW

**Comment by domialex** [comment]
I need someone else's opinion on this. I like the fact that it's configurable, but having so many strings makes me wonder if we should have sub-sections in `IUILanguage.cs`. For example, instead of `Language.BetrayalAislingTransportaion`, we would have `Language.CheatSheets.Betrayal.AislingTransportaion`?
Also, would it be a good feature to allow the user to choose which one is green/red/yellow?

**Comment by JadedCricket** [comment]
> I need someone else's opinion on this. I like the fact that it's configurable, but having so many strings makes me wonder if we should have sub-sections in `IUILanguage.cs`. For example, instead of `Language.BetrayalAislingTransportaion`, we would have `Language.CheatSheets.Betrayal.AislingTransportaion`?
> Also, would it be a good feature to allow the user to choose which one is green/red/yellow?

We may want to rework localization to use resource files. It's definitely Microsoft's recommended approach. https://docs.microsoft.com/en-us/dotnet/standard/globalization-localization/globalization#use-resource-files

If we go that route then I don't think it matters what we do it for this pull request as long as we have it on our radar to clean things up later.

**Comment by leMicin** [comment]
I really like the fact that we are not simply using an image.

I agree maybe we should move to DotNetCore's way of doing localization. At least for the UI parts.

**Comment by Zalhera** [comment]
I also had the idea to let the user choose the colors for himself but couldn't finish it in time.
Yes moving to resource files for the UI translation is the better approach and should definitely be done in the future. 
I just didn't have the time to look into this atm.
Just wanted to open the pr so that other people could work on the overview the self if they want.

**Pull request merged**
