### PR TITLE
Fix windows scaling causing overlay to display in the wrong position

### LINKED ISSUE #36: Overlay position doesn't seem to take into account 2 displays in some cases
[Image](https://imgur.com/a/y5p5mGf#w5McLO3)

### PR DESCRIPTION
**Pull request by vestakip**
Fixes #36.

Works for every combination I've tried but should probably be tested by people with different screen setups as well.

### CODE REVIEW

**Comment by dsolymosi** [comment]
I found two issues:
1. Popup seems to always be on first display, regardless of which display poe is on 
2. I was able to get the popup to be halfway off my monitor vertically, by querying on a monitor vertically above the first display:
pull-request-39

**Comment by domialex** [comment]
Is this line the culprit? `var screen = SystemParameters.WorkArea`

**Comment by vestakip** [comment]
Updated the hotfix to address the two issues @dsolymosi noted.

Only remaining issue I am aware of is I can't figure out any way to get the per-monitor scale factor, the way I'm doing it now always seems to return 144 dpi (150%) for me even if I drag my path of exile window onto my 96 dpi secondary. This means the positioning will be incorrect on secondary monitors if they do not have the same scale factory as the primary. I don't think this will be an issue for the vast majority of users so not a high priority to fix but if anyone has any ideas.

**Comment by domialex** [comment]
@vestakip I'm sorry about the conflicts, but I had to sync the dev branch with master.
We will try to make PRs only on develop from now .

**Comment by vestakip** [comment]
Fixed conflicts and updated PR to be for the develop branch.

**Pull request merged**
