### PR TITLE
Add corrupted option to equipable query

### LINKED ISSUE #53: Differentiate between corrupted and non-corrupted items
I'm price checking Shaper's Touch with the result the price being 5c, although this being the price for a pair of corrupted shaper's touch. Non corrupted are currently ~24c.

### PR DESCRIPTION
**Pull request by vonkez**
- Added corrupted option to equipable query
- Fixed #53

### CODE REVIEW

**Comment by Qwiso** [comment]
Hm. You've implemented this such that: when querying a corrupted item it will always search for a corrupted item. Or vice-versa

The issue is that the query does not show if the result is corrupted or not
Not to filter the query based on corrupted status, which would be a feature of adv. searching

I have a better solution to #53 but you've made this pull request just 30 minutes before I finished it

**Comment by Zalhera** [comment]
This should be some of the configurable search options mentioned in #63 
I'm not sure if it's a good idea to add this always as default search option

**Comment by vonkez** [comment]
I know making this option configurable definitely a better idea but I think until we have a configuration gui, making this default will be more useful.

**Comment by domialex** [comment]
Will be done in #74.

**Pull request closed without merging**
