### PR TITLE
Close overlay with mouse click setting & CTRL + Scroll optional

### PR DESCRIPTION
**Pull request by cmos12345**

### CODE REVIEW

**Comment by domialex** [comment]
@leMicin Do you want me to wait before merging this?

**Comment by leMicin** [comment]
Yeah these settings will need to be recoded. Sorry cmos. They are great additions, it is just that the Settings were being rewritten, and a ton has changed.

Keep the PR open, until we hear from @cmos12345

**Comment by leMicin** [comment]
This PR is broken because of #167 . Sorry

**Comment by cmos12345** [comment]
I see. Guess I'll rewrite it then hahaha :D

**Comment by cmos12345** [comment]
Closing this PR and opening a new one, since I implemented the rewritten logic in another branch

**Pull request closed without merging**
